### ISSUE TITLE
Parsing of youtube linked videos and linked images in chat

### ISSUE THREAD

**Issue by o-eazy** [prodikos/tpp-radio-ract-native#6]
There is a problem with the parsing of linked youtube videos and linked images in tpp chat.
Specifically, it does not show the correct url ,but rather it shows "source code".

For instance instead of a linked image it shows `<img src="media_icon/photolink.gif"/>`
Similarly for youtube links it shows `<img src="media_icon/youtube.gif"/>&amp;list=LLvo......`

**Comment by prodikos** [comment]
Good point 👍 I don't do a second-level parsing when I find an image or a youtube link
